server:
  port: 8087

spring:
  datasource:
    username: root
    password: root
#    password: Password01!
#    url: jdbc:mysql://10.200.100.1:3306/iqa_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/iqa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    host: 10.200.100.1
    port: 6379
    password:
    sentinel:
      master: mymaster
      nodes: 10.200.100.1:26379,10.200.100.2:26379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    timeout: 0
mybatis-plus:
  #开启sql  日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yechtech.dac.user.domain,com.yechtech.dac.job.domain,com.yechtech.dac.system.domain,
  global-config:
    banner: false

dap:
  url: http://localhost:8081/

logging:
  config: classpath:logback-spring.xml


